 Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"my-dep1"},"name":"my-dep1","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"my-dep1"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"my-dep1"}},"spec":{"containers":[{"image":"localhost:32000/project:registry","name":"project","resources":{}}]}}},"status":{}}
  creationTimestamp: "2020-04-22T17:11:12Z"
  generation: 3
  labels:
    app: my-dep1
  name: my-dep1
  namespace: default
  resourceVersion: "104461"
  selfLink: /apis/apps/v1/namespaces/default/deployments/my-dep1
  uid: 25fac5dd-f3fb-40a3-a9fd-6a06ac5eb0ab
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-dep1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep1
    spec:
      containers:
      - image: localhost:32000/project:registry
        imagePullPolicy: IfNotPresent
        name: project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-04-22T17:11:12Z"
    lastUpdateTime: "2020-04-22T17:12:06Z"
    message: ReplicaSet "my-dep1-87597cd8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-22T17:28:26Z"
    lastUpdateTime: "2020-04-22T17:28:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
