# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-04-22T18:59:50Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-04-22T18:59:50Z","reason":"FailedGetResourceMetric","message":"the
      HPA was unable to compute the replica count: missing request for cpu"}]'
  creationTimestamp: "2020-04-22T18:59:35Z"
  name: my-dep1
  namespace: default
  resourceVersion: "123813"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/my-dep1
  uid: 9747c9f4-bc5e-4518-bdb5-1e428fc72d41
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-dep1
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 3
  desiredReplicas: 0
