# Generated by Django 3.0.5 on 2020-04-21 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 12, 46, 44, 867630, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='projectmentor',
            name='mentor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orientation.User'),
        ),
        migrations.AddField(
            model_name='projectmentor',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orientation.Project'),
        ),
        migrations.AddField(
            model_name='projectmentee',
            name='mentee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orientation.User'),
        ),
        migrations.AddField(
            model_name='projectmentee',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orientation.Project'),
        ),
    ]
