# Generated by Django 3.0.5 on 2020-04-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_auto_20200421_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
